targets:
    prod:
        host: dev.astrotraker.com
        path: /var/www/com.astrotraker
        ssh:
            user: msmith
#            password: pass
    prod2:
        host: dev.astrotraker.com
        path: /var/www/com.astrotraker
        ssh:
            user: msmith
#            password: pass
